{"level":"ERROR","location":"[exception:108] fyers_logger","message":"name 'json' is not defined","timestamp":"2025-10-22 09:55:57,519+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\eldoj\\PycharmProjects\\S.E.N.T.R.Y\\data\\fyers_client.py\", line 127, in _on_message\n    data = json.loads(message)\nNameError: name 'json' is not defined","exception_name":"NameError"}
{"level":"ERROR","location":"[On_message:1447] data_ws","message":"name 'json' is not defined","timestamp":"2025-10-22 09:55:57,529+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"name 'json' is not defined","timestamp":"2025-10-22 09:55:57,663+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\eldoj\\PycharmProjects\\S.E.N.T.R.Y\\data\\fyers_client.py\", line 127, in _on_message\n    data = json.loads(message)\nNameError: name 'json' is not defined","exception_name":"NameError"}
{"level":"ERROR","location":"[On_message:1447] data_ws","message":"name 'json' is not defined","timestamp":"2025-10-22 09:55:57,664+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"local variable 'hsm_symbol' referenced before assignment","timestamp":"2025-10-22 09:55:59,447+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\nUnboundLocalError: local variable 'hsm_symbol' referenced before assignment","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"'NoneType' object is not subscriptable","timestamp":"2025-10-22 09:55:59,450+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"the JSON object must be str, bytes or bytearray, not dict","timestamp":"2025-10-22 09:59:49,871+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\eldoj\\PycharmProjects\\S.E.N.T.R.Y\\data\\fyers_client.py\", line 130, in _on_message\n    data = json.loads(message)\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\json\\__init__.py\", line 339, in loads\n    raise TypeError(f'the JSON object must be str, bytes or bytearray, '\nTypeError: the JSON object must be str, bytes or bytearray, not dict","exception_name":"TypeError"}
{"level":"ERROR","location":"[On_message:1447] data_ws","message":"the JSON object must be str, bytes or bytearray, not dict","timestamp":"2025-10-22 09:59:49,883+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"the JSON object must be str, bytes or bytearray, not dict","timestamp":"2025-10-22 09:59:50,075+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\eldoj\\PycharmProjects\\S.E.N.T.R.Y\\data\\fyers_client.py\", line 130, in _on_message\n    data = json.loads(message)\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\json\\__init__.py\", line 339, in loads\n    raise TypeError(f'the JSON object must be str, bytes or bytearray, '\nTypeError: the JSON object must be str, bytes or bytearray, not dict","exception_name":"TypeError"}
{"level":"ERROR","location":"[On_message:1447] data_ws","message":"the JSON object must be str, bytes or bytearray, not dict","timestamp":"2025-10-22 09:59:50,077+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"local variable 'hsm_symbol' referenced before assignment","timestamp":"2025-10-22 09:59:51,769+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\nUnboundLocalError: local variable 'hsm_symbol' referenced before assignment","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"'NoneType' object is not subscriptable","timestamp":"2025-10-22 09:59:51,774+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"Connection to remote host was lost.","timestamp":"2025-10-22 10:00:37,538+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"the JSON object must be str, bytes or bytearray, not dict","timestamp":"2025-10-22 10:00:42,798+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\eldoj\\PycharmProjects\\S.E.N.T.R.Y\\data\\fyers_client.py\", line 130, in _on_message\n    data = message\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\json\\__init__.py\", line 339, in loads\n    raise TypeError(f'the JSON object must be str, bytes or bytearray, '\nTypeError: the JSON object must be str, bytes or bytearray, not dict","exception_name":"TypeError"}
{"level":"ERROR","location":"[On_message:1447] data_ws","message":"the JSON object must be str, bytes or bytearray, not dict","timestamp":"2025-10-22 10:00:42,801+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"the JSON object must be str, bytes or bytearray, not dict","timestamp":"2025-10-22 10:00:42,975+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\eldoj\\PycharmProjects\\S.E.N.T.R.Y\\data\\fyers_client.py\", line 130, in _on_message\n    data = message\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\json\\__init__.py\", line 339, in loads\n    raise TypeError(f'the JSON object must be str, bytes or bytearray, '\nTypeError: the JSON object must be str, bytes or bytearray, not dict","exception_name":"TypeError"}
{"level":"ERROR","location":"[On_message:1447] data_ws","message":"the JSON object must be str, bytes or bytearray, not dict","timestamp":"2025-10-22 10:00:42,976+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"local variable 'hsm_symbol' referenced before assignment","timestamp":"2025-10-22 10:02:46,434+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\nUnboundLocalError: local variable 'hsm_symbol' referenced before assignment","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"'NoneType' object is not subscriptable","timestamp":"2025-10-22 10:02:46,437+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"Connection to remote host was lost.","timestamp":"2025-10-22 10:06:03,773+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"local variable 'hsm_symbol' referenced before assignment","timestamp":"2025-10-22 10:08:44,701+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\nUnboundLocalError: local variable 'hsm_symbol' referenced before assignment","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"'NoneType' object is not subscriptable","timestamp":"2025-10-22 10:08:44,703+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"Connection to remote host was lost.","timestamp":"2025-10-22 10:12:55,590+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"local variable 'hsm_symbol' referenced before assignment","timestamp":"2025-10-22 10:18:52,614+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\nUnboundLocalError: local variable 'hsm_symbol' referenced before assignment","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"'NoneType' object is not subscriptable","timestamp":"2025-10-22 10:18:52,616+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"Connection to remote host was lost.","timestamp":"2025-10-22 11:41:54,100+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"local variable 'hsm_symbol' referenced before assignment","timestamp":"2025-10-22 11:55:53,107+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\nUnboundLocalError: local variable 'hsm_symbol' referenced before assignment","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"'NoneType' object is not subscriptable","timestamp":"2025-10-22 11:55:53,111+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"Connection to remote host was lost.","timestamp":"2025-10-22 12:57:48,538+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"local variable 'hsm_symbol' referenced before assignment","timestamp":"2025-10-23 10:17:59,991+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\nUnboundLocalError: local variable 'hsm_symbol' referenced before assignment","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"'NoneType' object is not subscriptable","timestamp":"2025-10-23 10:17:59,998+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"local variable 'hsm_symbol' referenced before assignment","timestamp":"2025-10-23 14:57:07,190+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\nUnboundLocalError: local variable 'hsm_symbol' referenced before assignment","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"'NoneType' object is not subscriptable","timestamp":"2025-10-23 14:57:07,195+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"local variable 'hsm_symbol' referenced before assignment","timestamp":"2025-10-23 15:00:35,329+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\nUnboundLocalError: local variable 'hsm_symbol' referenced before assignment","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"'NoneType' object is not subscriptable","timestamp":"2025-10-23 15:00:35,331+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"Connection to remote host was lost.","timestamp":"2025-10-23 15:01:23,043+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"local variable 'hsm_symbol' referenced before assignment","timestamp":"2025-10-23 15:10:29,041+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\nUnboundLocalError: local variable 'hsm_symbol' referenced before assignment","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"'NoneType' object is not subscriptable","timestamp":"2025-10-23 15:10:29,045+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"local variable 'hsm_symbol' referenced before assignment","timestamp":"2025-10-23 15:13:52,382+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\nUnboundLocalError: local variable 'hsm_symbol' referenced before assignment","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"'NoneType' object is not subscriptable","timestamp":"2025-10-23 15:13:52,384+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"local variable 'hsm_symbol' referenced before assignment","timestamp":"2025-10-23 15:18:01,539+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\nUnboundLocalError: local variable 'hsm_symbol' referenced before assignment","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"'NoneType' object is not subscriptable","timestamp":"2025-10-23 15:18:01,541+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\eldoj\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
